version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: stats_server
    container_name: stats_server
    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm


  ewm-service:
      build: ewm-service
      image: ewm_service
      container_name: ewm_service
      ports:
        - "8080:8080"

      depends_on:
        - ewm-db
      environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5442/ewm
      - SPRING_DATASOURCE_USERNAME=ewmservice
      - SPRING_DATASOURCE_PASSWORD=ewmservice


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm
    ports:
      - "5442:5442"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

